api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }

api_get:
    path:     /get
    defaults: { _controller: ApiBundle:Default:index }

index:
    path:     /member
    defaults: { _controller: ApiBundle:Member:index }
