services:
    api.action_resolver:
        class: ApiBundle\Services\ActionResolver
        arguments: ["@api.action_factory", "@jms_serializer"]

    api.action_factory:
        class: ApiBundle\Services\ActionFactory
        arguments: ["@doctrine.orm.entity_manager", "@api.security_jws_provider"]

    api.security_jws_provider:
            class: ApiBundle\Services\Security\JWSProvider
            arguments: []
