services:
    api.action_resolver:
        class: ApiBundle\Services\ActionResolver
        arguments: ["@api.action_factory", "@jms_serializer"]

    api.action_factory:
        class: ApiBundle\Services\ActionFactory
        arguments: ["@doctrine.orm.entity_manager"]
