ApiBundle\Entity\Address:
    type: entity
    table: null
    repositoryClass: ApiBundle\Repository\AddressRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        cityId:
            type: integer
            column: city_id
            nullable: true
        regionId:
            type: integer
            column: region_id
            nullable: true
    lifecycleCallbacks: {  }
    manyToOne:
        region:
            targetEntity: Region
            joinColumn:
                name: region_id
                referencedColumnName: id
        city:
            targetEntity: City
            joinColumn:
                name: city_id
                referencedColumnName: id