ApiBundle\Entity\Member:
    type: entity
    table: null
    repositoryClass: ApiBundle\Repository\MemberRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        email:
            type: string
            length: 255
        password:
            type: string
            length: 255
        isActive:
            type: boolean
            column: is_active
    lifecycleCallbacks: {  }
